apiVersion: v1
kind: ReplicationController
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: account-service
    spec:
      containers:
      - name: account-service
        image: gcr.io/hack-gcph-7/account-service:v1
        ports:
        - containerPort: 2222
          protocol: TCP