apiVersion: v1
kind: ReplicationController
metadata:
  name: customer-service-v2
  labels:
    run: customer-service
spec:
  replicas: 3
  selector:
    name: customer-service
    version: v2
  #our pod template
  template:
    metadata:
      labels:
        name: customer-service
        run: customer-service
        version: v2
    spec:
      containers:
      - name: customer-service
        image: gcr.io/hack-gcph-7/customer-service:v2
        ports:
        - containerPort: 3333
          protocol: TCP