apiVersion: v1
kind: ReplicationController
metadata:
  name: customer-service
  labels:
    run: customer-service
spec:
  replicas: 2
  selector:
    name: customer-service
    version: v1
  #our pod template
  template:
    metadata:
      labels:
        name: customer-service
        run: customer-service
        version: v1
    spec:
      containers:
      - name: customer-service
        image: gcr.io/hack-gcph-7/customer-service:v1
        ports:
        - containerPort: 3333
          protocol: TCP